# Generated by Django 4.2.13 on 2024-05-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
    ]
